package com.newssentiment.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DTO for AI-generated narrative analysis summary.
 * This represents the structured analysis generated by Claude Haiku
 * for auto-detected narrative clusters.
 */
public record AiSummaryDTO(
        @JsonProperty("why_detected")
        String whyDetected,

        @JsonProperty("spread_pattern")
        String spreadPattern,

        @JsonProperty("threat_signal")
        String threatSignal,

        @JsonProperty("suggested_title")
        String suggestedTitle,

        @JsonProperty("analyst_note")
        String analystNote
) {}
