package com.newssentiment.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.newssentiment.dto.NarrativeDTO;
import com.newssentiment.model.ThreatAlert;
import com.newssentiment.repository.ArticleRepository;
import com.newssentiment.repository.ThreatAlertRepository;
import com.newssentiment.security.OrganizationContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;

/**
 * Service for generating PDF reports.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class PdfExportService {

    private final NarrativeService narrativeService;
    private final ThreatAlertService alertService;
    private final ArticleRepository articleRepository;
    private final ThreatAlertRepository alertRepository;

    private static final DateTimeFormatter DATE_FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());
    private static final DateTimeFormatter DATE_ONLY_FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd").withZone(ZoneId.systemDefault());

    // Colors
    private static final Color HEADER_BG = new Color(52, 73, 94);
    private static final Color CRITICAL_COLOR = new Color(142, 68, 173);
    private static final Color HIGH_COLOR = new Color(231, 76, 60);
    private static final Color MEDIUM_COLOR = new Color(243, 156, 18);
    private static final Color LOW_COLOR = new Color(52, 152, 219);

    /**
     * Generate a weekly summary report PDF.
     */
    @Transactional(readOnly = true)
    public byte[] generateWeeklyReport() throws DocumentException {
        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        PdfWriter.getInstance(document, out);
        document.open();

        // Title
        Font titleFont = new Font(Font.HELVETICA, 24, Font.BOLD, HEADER_BG);
        Paragraph title = new Paragraph("AIIM Weekly Intelligence Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(10);
        document.add(title);

        // Subtitle with date range
        Instant now = Instant.now();
        Instant weekAgo = now.minus(7, ChronoUnit.DAYS);
        Font subtitleFont = new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY);
        Paragraph subtitle = new Paragraph(
                DATE_ONLY_FORMATTER.format(weekAgo) + " to " + DATE_ONLY_FORMATTER.format(now),
                subtitleFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(30);
        document.add(subtitle);

        // Executive Summary
        addSectionTitle(document, "Executive Summary");
        addExecutiveSummary(document);

        // Top Narratives
        addSectionTitle(document, "Top Narratives");
        addNarrativesTable(document);

        // Recent Alerts
        addSectionTitle(document, "Recent Critical Alerts");
        addAlertsTable(document);

        // Footer
        Font footerFont = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);
        Paragraph footer = new Paragraph(
                "\nGenerated by AIIM (AI Information Integrity Monitor) on " +
                        DATE_FORMATTER.format(now),
                footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    /**
     * Generate a narrative-specific incident report.
     */
    @Transactional(readOnly = true)
    public byte[] generateNarrativeReport(Long narrativeId) throws DocumentException {
        NarrativeDTO narrative = narrativeService.findById(narrativeId)
                .orElseThrow(() -> new IllegalArgumentException("Narrative not found: " + narrativeId));

        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        PdfWriter.getInstance(document, out);
        document.open();

        // Title
        Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, HEADER_BG);
        Paragraph title = new Paragraph("Incident Report: " + narrative.name(), titleFont);
        title.setSpacingAfter(20);
        document.add(title);

        // Narrative details
        addSectionTitle(document, "Overview");

        Font labelFont = new Font(Font.HELVETICA, 10, Font.BOLD);
        Font valueFont = new Font(Font.HELVETICA, 10, Font.NORMAL);

        Paragraph details = new Paragraph();
        details.add(new Chunk("Status: ", labelFont));
        details.add(new Chunk(narrative.status() + "\n", valueFont));
        details.add(new Chunk("Threat Level: ", labelFont));
        details.add(new Chunk(narrative.threatLevel() + "\n", valueFont));
        details.add(new Chunk("First Seen: ", labelFont));
        details.add(new Chunk(narrative.firstSeen() != null ?
                DATE_FORMATTER.format(narrative.firstSeen()) : "Unknown" + "\n", valueFont));
        details.add(new Chunk("Total Articles: ", labelFont));
        details.add(new Chunk(narrative.articleCount() + "\n", valueFont));
        details.add(new Chunk("Keywords: ", labelFont));
        details.add(new Chunk(String.join(", ", narrative.keywords()) + "\n", valueFont));
        details.setSpacingAfter(15);
        document.add(details);

        // Description
        if (narrative.description() != null && !narrative.description().isEmpty()) {
            addSectionTitle(document, "Description");
            Paragraph desc = new Paragraph(narrative.description(), valueFont);
            desc.setSpacingAfter(15);
            document.add(desc);
        }

        // Related alerts
        addSectionTitle(document, "Related Alerts");
        addNarrativeAlerts(document, narrativeId);

        // Footer
        Font footerFont = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);
        Paragraph footer = new Paragraph(
                "\nGenerated by AIIM on " + DATE_FORMATTER.format(Instant.now()),
                footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addSectionTitle(Document document, String title) throws DocumentException {
        Font sectionFont = new Font(Font.HELVETICA, 14, Font.BOLD, HEADER_BG);
        Paragraph section = new Paragraph(title, sectionFont);
        section.setSpacingBefore(15);
        section.setSpacingAfter(10);
        document.add(section);
    }

    private void addExecutiveSummary(Document document) throws DocumentException {
        Long orgId = OrganizationContext.getCurrentOrganizationIdOrNull();
        Instant weekAgo = Instant.now().minus(7, ChronoUnit.DAYS);

        long totalArticles = articleRepository.countSince(weekAgo);
        long activeAlerts = alertService.countActive();
        long activeNarratives = narrativeService.countActive();

        Font textFont = new Font(Font.HELVETICA, 11, Font.NORMAL);

        String summary = String.format(
                "This week, AIIM monitored %d articles across Armenian media sources. " +
                        "Currently tracking %d active narratives with %d active alerts requiring attention. ",
                totalArticles, activeNarratives, activeAlerts);

        Paragraph para = new Paragraph(summary, textFont);
        para.setSpacingAfter(15);
        document.add(para);
    }

    private void addNarrativesTable(Document document) throws DocumentException {
        List<NarrativeDTO> narratives = narrativeService.findTopByArticleCount(5);

        if (narratives.isEmpty()) {
            document.add(new Paragraph("No active narratives.", new Font(Font.HELVETICA, 10)));
            return;
        }

        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3, 1.5f, 1, 1.5f});

        // Headers
        addTableHeader(table, "Narrative");
        addTableHeader(table, "Threat Level");
        addTableHeader(table, "Articles");
        addTableHeader(table, "Status");

        // Data rows
        for (NarrativeDTO narrative : narratives) {
            table.addCell(createCell(narrative.name(), false));
            table.addCell(createThreatLevelCell(narrative.threatLevel()));
            table.addCell(createCell(String.valueOf(narrative.articleCount()), false));
            table.addCell(createCell(narrative.status(), false));
        }

        document.add(table);
    }

    private void addAlertsTable(Document document) throws DocumentException {
        Long orgId = OrganizationContext.getCurrentOrganizationIdOrNull();
        Instant weekAgo = Instant.now().minus(7, ChronoUnit.DAYS);

        List<ThreatAlert> alerts = orgId != null
                ? alertRepository.findByOrganizationIdAndTriggeredSince(orgId, weekAgo)
                : alertRepository.findTriggeredSince(weekAgo);

        // Filter to HIGH and CRITICAL only
        alerts = alerts.stream()
                .filter(a -> a.getSeverity() == ThreatAlert.Severity.HIGH ||
                        a.getSeverity() == ThreatAlert.Severity.CRITICAL)
                .limit(10)
                .toList();

        if (alerts.isEmpty()) {
            document.add(new Paragraph("No critical alerts in the past week.",
                    new Font(Font.HELVETICA, 10)));
            return;
        }

        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3, 1.2f, 1.2f, 2});

        addTableHeader(table, "Alert");
        addTableHeader(table, "Severity");
        addTableHeader(table, "Status");
        addTableHeader(table, "Triggered");

        for (ThreatAlert alert : alerts) {
            table.addCell(createCell(truncate(alert.getTitle(), 50), false));
            table.addCell(createSeverityCell(alert.getSeverity().name()));
            table.addCell(createCell(alert.getStatus().name(), false));
            table.addCell(createCell(DATE_FORMATTER.format(alert.getTriggeredAt()), false));
        }

        document.add(table);
    }

    private void addNarrativeAlerts(Document document, Long narrativeId) throws DocumentException {
        Long orgId = OrganizationContext.getCurrentOrganizationIdOrNull();

        List<ThreatAlert> alerts = orgId != null
                ? alertRepository.findByOrganizationIdAndNarrativeId(orgId, narrativeId)
                : alertRepository.findByNarrativeId(narrativeId);

        alerts = alerts.stream().limit(10).toList();

        if (alerts.isEmpty()) {
            document.add(new Paragraph("No alerts for this narrative.",
                    new Font(Font.HELVETICA, 10)));
            return;
        }

        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3, 1.5f, 2});

        addTableHeader(table, "Alert");
        addTableHeader(table, "Severity");
        addTableHeader(table, "Date");

        for (ThreatAlert alert : alerts) {
            table.addCell(createCell(truncate(alert.getTitle(), 60), false));
            table.addCell(createSeverityCell(alert.getSeverity().name()));
            table.addCell(createCell(DATE_FORMATTER.format(alert.getTriggeredAt()), false));
        }

        document.add(table);
    }

    private void addTableHeader(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text,
                new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE)));
        cell.setBackgroundColor(HEADER_BG);
        cell.setPadding(5);
        table.addCell(cell);
    }

    private PdfPCell createCell(String text, boolean bold) {
        Font font = new Font(Font.HELVETICA, 9, bold ? Font.BOLD : Font.NORMAL);
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(4);
        return cell;
    }

    private PdfPCell createSeverityCell(String severity) {
        Color bgColor = switch (severity) {
            case "CRITICAL" -> CRITICAL_COLOR;
            case "HIGH" -> HIGH_COLOR;
            case "MEDIUM" -> MEDIUM_COLOR;
            default -> LOW_COLOR;
        };

        PdfPCell cell = new PdfPCell(new Phrase(severity,
                new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE)));
        cell.setBackgroundColor(bgColor);
        cell.setPadding(4);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }

    private PdfPCell createThreatLevelCell(String level) {
        return createSeverityCell(level); // Same color coding
    }

    private String truncate(String text, int maxLength) {
        if (text == null) return "";
        return text.length() > maxLength ? text.substring(0, maxLength) + "..." : text;
    }
}
